### ISSUE TITLE
installation typo?

### ISSUE THREAD

**Issue by mebrooks** [iagomosqueira/mseExamples#1]
Installation instructions [here](https://github.com/iagomosqueira/mseExamples#installation) say to use
`remotes::install_github(paste("flr", c("FLCore", "FLFishery", "FLasher", "mse")))` but it doesn't work.

```
> remotes::install_github(paste("flr", c("FLCore", "FLFishery", "FLasher", "mse")))
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'flr FLCore'
```

**Comment by iagomosqueira** [comment]
Missing sep

remotes::install_github(paste("flr", c("FLCore", "FLFishery", "FLasher", "mse"), sep="/"))
